report.py: Fix error raised when running "did arrive"
This error was introduced in 489f6edeb82a9584d59a56db0818616689f3be0d
("report.py: Extract SessionChronologicalDisplay()").

The following output was printed on running `did arrive`:

  2012-08-23
  Traceback (most recent call last):
    File "src/did.py", line 149, in <module>
      did.run()
    File "src/did.py", line 67, in run
      report.display(DayRange(self.options.range))
    File "/home/ahven/dev/time-management/did/src/report.py", line 140, in display
      self._print_session(session, stats)
    File "/home/ahven/dev/time-management/did/src/report.py", line 146, in _print_session
      self._print_log_line(
  AttributeError: JobReport instance has no attribute '_print_log_line'